
services:
  superbike.api:
    image: ${DOCKER_REGISTRY-}superbikeapi
    build:
      context: .
      dockerfile: src/SuperBike.Api/Dockerfile
    ports: 
     - "8081:8080"
    environment:
     ConnectionsString: "Host:hostdbsuperbike;Database:superbikedb;Username:postgres;Password:postgres"
    depends_on:
     - hostdbsuperbike
    networks:
     netsuperbike:

  hostdbsuperbike:
    container_name: hostdbsuperbike
    image: postgres
    ports: 
     - "5432:5432"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: superbikedb
     PGPORT: 5432
    volumes:
     - pgdata-superbikedb:/var/lib/postgresql/data
    networks:
     netsuperbike:
#<rabbitmq>     
  rabbitmq:
    container_name: rabbitmq
    tty: true
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
#</rabbitmq>     

volumes:
  pgdata-superbikedb: {}

networks:
  netsuperbike:
    