
services:
  superbikeapi: #Api
    image: ${DOCKER_REGISTRY-}superbikeapi
    build:
      context: .
      dockerfile: src/SuperBike.Api/Dockerfile
    ports: 
     - "8081:8080"

    depends_on:
     - postgres
     - rabbitmq
     - seq
    networks:
     netsuperbike:

  superbikefilestorage: #FileStorage
    image: ${DOCKER_REGISTRY-}superbikefilestorage
    build:
      context: .
      dockerfile: src/SuperBike.Api.FileStorage/Dockerfile
    ports: 
     - "8082:8080"
    environment:
     ConnectionsString: "Host:postgres;Database:superbikedb;Username:postgres;Password:postgres"
    depends_on:
     - postgres
     - seq
    networks:
     netsuperbike:

  superbikeconsumer: #Consumer
    image: ${DOCKER_REGISTRY-}superbikeconsumer
    build:
      context: .
      dockerfile: src/SuperBike.Consumer/Dockerfile
    ports: 
     - "8083:8080"
    environment:
     ConnectionsString: "Host:postgres;Database:superbikedb;Username:postgres;Password:postgres"
    depends_on:
     - postgres
     - rabbitmq
     - seq
    networks:
     netsuperbike:

#<postgres>
  postgres:
    container_name: postgres
    image: postgres
    ports: 
     - "5432:5432"
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: superbikedb
     PGPORT: 5432
    volumes:
     #- pgdata-superbikedb:/var/lib/postgresql/data
     - ./src/SuperBike.Infrastructure/ChangesDB/1.0.0/01_DDL.sql:/docker-entrypoint-initdb.d/01_DDL.sql
     - ./src/SuperBike.Infrastructure/ChangesDB/1.0.0/02_DML.sql:/docker-entrypoint-initdb.d/02_DML.sql
    networks:
     netsuperbike:
#</postgres>     

#<rabbitmq>
  rabbitmq:
    container_name: rabbitmq
    tty: true
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
     netsuperbike:      
#</rabbitmq>

#<seq>
  seq:
    container_name: seq    
    hostname: seq
    ports:
      - "5341:5341"      
      - "81:80"
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y      
    networks:
     netsuperbike:
  #---
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped     
#</seq>

#volumes:
  #pgdata-superbikedb: {}

networks:
  netsuperbike:
    